### ISSUE TITLE
Feature Request: Allow users to cancel the elevation request

### ISSUE THREAD

**Issue by dan-snelson** [robjschroeder/Elevate#18]
@robjschroeder: 

Thanks for all your work on `2.0.0`!

Looks like there's no way to "cancel" an elevation request, I can only provide a reason and elevate.

**Comment by robjschroeder** [comment]
Hey @dan-snelson , would you mind trying out version 2.0.1 in the development branch and let me know how it goes? https://github.com/robjschroeder/Elevate/blob/development/Elevate.sh

**Comment by dan-snelson** [comment]
The cancel feature in a customized version of `2.0.1` is working as expected.

Thanks.
