### ISSUE TITLE
Improve initial launch speed

### ISSUE THREAD

**Issue by robjschroeder** [robjschroeder/Elevate#20]
- Moving the initial recon later in the script will improve the speed at which the prompt dialog is shown
- If a webhook is not being used, no need for initial recon.

**Comment by robjschroeder** [comment]
Thanks for the idea @dan-snelson !

**Comment by dan-snelson** [comment]
Go Rob! Go Rob! Go Rob!

**Comment by robjschroeder** [comment]
Launch speed has been greatly improved for a much better user experience.
