### ISSUE TITLE
Feature Request: Add `toggleJamfLaunchDaemon` code

### ISSUE THREAD

**Issue by dan-snelson** [robjschroeder/Elevate#21]
Rob:

One of our users just experienced a hiccup (which might not be an edge-case).

After using Elevate to attempt the installation of a macOS Sonoma beta, the `jamf` binary ran an unrelated policy which then removed local admin rights.

What about adding [your code](https://github.com/dan-snelson/Setup-Your-Mac/blob/1.12.0/Setup-Your-Mac-via-Dialog.bash#L317-L370) from SYM to ensure other, unrelated policies are "paused" ?

**Comment by robjschroeder** [comment]
Hey @dan-snelson , I've added this function to version 2.0.2 in the development branch. Feel free to test when you get a chance!
