### ISSUE TITLE
Update swiftDialog URL

### ISSUE THREAD

**Issue by mobofixer** [robjschroeder/Elevate#30]
the URL for dialog has been updated.

To correct this in the script update line 151:
`dialogURL=$(curl --silent --fail "https://api.github.com/repos/bartreardon/swiftDialog/releases/latest" | awk -F '"' "/browser_download_url/ && /pkg\"/ { print \$4; exit }")`
… to:
`dialogURL=$(curl -L --silent --fail "https://api.github.com/repos/swiftDialog/swiftDialog/releases/latest" | awk -F '"' "/browser_download_url/ && /pkg\"/ { print \$4; exit }")`

**Comment by robjschroeder** [comment]
Thanks @mobofixer, changed in `2.0.6` #31
