### ISSUE TITLE
Warn if user is already a local admin

### ISSUE THREAD

**Issue by mobofixer** [robjschroeder/Elevate#9]
If a user is already a local admin (prior to running the script) it would be nice if the script stopped running and let the user know they are already an admin and not demote them down to standard user.

**Comment by robjschroeder** [comment]
Good afternoon @mobofixer. Please check version 2.0.0-b1, if you do not desire admin rights to be removed set the appropriate variable to `false`, Elevate will not continue through the process if the user is already an admin user. It is expected in this case, the user will not see a timer session.

**Comment by robjschroeder** [comment]
This is resolved in version 2.0.0
